# Generated by Django 5.1.4 on 2025-01-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='question_paper_id',
            new_name='paper_id',
        ),
        migrations.RemoveField(
            model_name='response',
            name='id',
        ),
        migrations.AddField(
            model_name='response',
            name='marks_awarded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='response_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='total_marks',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
